language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

cache:
  pip: true
  directories:
    - $HOME/.cache

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=predicthq tests/

after_success:
  - coveralls

notifications:
  slack:
    secure: Mi4B2z6X0tE2vyfuF359/eXAxu8IgnOWT6REHBGYTGfB+baKtowBmQeMBTXe6aZFUuQ4vgnZAiq7KWgBwkpv4RuaP1BO9XkPwlnfXQOv6u4nIECGJcTiE4XTMl6zX1r4Km0X6kD9jP+Rvm6YCE6eiDf+xqLsMwECQstXYehwrT53fXnOYXhqP2girK+BFhJ5M2OYvz/K+kC+rMOGQjddic9SkNDYczTo22kVJ3OhIBkEC95UkfcFBEGE5/LP25zON9ptXv73aiuWjCNeaO/YBKog/hRJyYPdlwdaY7ENYiJHFCz/dRqDv32cNy28TTzdDOuE5Jic1OTMfvG2xnSjBZA/7R+msHqoVJ6Wn+IGlKvHCc4/etVoNpGyv7/tuXwAIY8s6ied4bLEvpSs/cEK0FMidZRcUoZ1+a2j28/rY7aqYef4sA0DwzplWMEoA680AAA4e0nGXIBbM6eb6aldd4oiIlW2F1PX0wGOXhdKYh7/rb2OxJ27rJTKsW8gbRN2OT3M9P5pdTAj5P7MmNIjKbJSxSemGhcfQIRl3FWn6oKIgQNbtWSkLEVh09JhjZJhnVlRtsPYr8rQQaMSc1EyQqDLicEB4lt0+Oe+Qq82HYWl6XfnzpTYc71mKrtjckdlDxBcAS9Rv1XNmBwQH9AbwcmifM0wOPJ5jiYXLmi4ucw=

before_deploy:
  - echo "__version__ = '$TRAVIS_TAG'" > predicthq/version.py

deploy:
  provider: pypi
  user: predicthq
  password:
    secure: MVqwC88f3OWpl9I6DILaJ9b9xAc58YdNTPdtWVvDHsc+kigBOnU6g1KLe/LF1JdUqxvxGTFd70t9b4FjCGeXDsQRq12BCVEuuCSZ1GD+nCo8cUcbAt0XBaIzgD04DpbUGA8vsofcPjnPAU/U3eQP2BJEhsaxWMQhqUi4WAbeUQ0he5BriXfu+Fs52b17i7leEWgEQyhhenKBi6+JO9ZdOKrRWGOmSaGWCnZzR4k6SeK5ZQ+Hd9EPIB0Cv8YVuOkAm0cCBZaIFAgUZGnAI4gbjioAmW52kCVCSddAzRN3eZy5D6blatWmz0WLuREwXNuBreu1Tswblv2EHPp8RCH9lMC9DSK9m3bp5SsDYeTnRXc3/Qew+543fj3VxCORx/K9Xdqra5OTLBk7Y51C+bRtUkB8xXMR96EJy/kEQXt3CR9GECReJNr0+nld+IrLQB7FV0w5RfCYy+Qu71iibSdfifu2aiRW8M2YOWw/BPLN0pufl6V9zauMKnfoCn0kctbYRL2yFaDHPR1krCAUGdQ0J0VUma0T3XhLDcsid3YYHgKsr1rhKOOcLUpm4H0p2HModC1Hggl0YWqC+Vr9n2zw2w29iUbafGnCtTif9O/yKwnQ2zK39nZMtQPXISQNTXhRkarQnahdEMZ1n0JrgetVcL4ek5RrKwMNDMk9CLH+q14=
  distributions: bdist_wheel
  on:
    tags: true
    repo: predicthq/sdk-py
    branch: master
    condition: $RELEASE_SENTINEL = 1
